#!/bin/sh
# droid-hal device add script
# Copyright (c) 2014 Jolla Ltd.
# Contact: Simonas Leleiva <simonas.leleiva@jollamobile.com>

if [ -z $DEVICE ]; then
    echo 'Error: $DEVICE is undefined. Please run hadk'
    exit 1
fi

ROOTFS_DIR=device-$VENDOR-$DEVICE-configs
PATTERNS_DIR=patterns
PATTERNS_DEVICE_DIR=$PATTERNS_DIR/$DEVICE
PATTERNS_TEMPLATES_DIR=$PATTERNS_DIR/templates

if [ ! -d rpm/$PATTERNS_TEMPLATES_DIR ]; then
    echo $0: launch this script from the $ANDROID_ROOT directory
    exit 1
fi

cd rpm/

if [ -e $ROOTFS_DIR ]; then
    read -p "Device $DEVICE appears to be already created. Re-generate patterns? [Y/n] " -n 1 -r
    REPLY=${REPLY:-Y}
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
else
    echo $ROOTFS_DIR/
    mkdir -p $ROOTFS_DIR
fi

echo Creating the following nodes:

echo $PATTERNS_DEVICE_DIR/

mkdir -p $PATTERNS_DEVICE_DIR

for pattern in jolla-configuration jolla-hw-adaptation; do
    PATTERNS_FILE=$PATTERNS_DEVICE_DIR/$pattern-$DEVICE.yaml
    cat <<EOF >$PATTERNS_FILE
# DO NOT MODIFY THIS FILE! AUTOGENERATED BY EXECUTING:
# helpers/add_new_device.sh $VENDOR $DEVICE
EOF
    sed -e 's|@DEVICE@|'$DEVICE'|g' $PATTERNS_TEMPLATES_DIR/$pattern-@DEVICE@.yaml >>$PATTERNS_FILE
    echo $PATTERNS_FILE
done

cd ..

