#!/bin/sh
# Fix up mount points in unit files
# FIXME: Right now, this is mako-specific

# This is broken pending systemd > 191-2 so hack the generated unit files :(
# See: https://bugzilla.redhat.com/show_bug.cgi?id=859297

if [[ x"$DEVICE" = x"mako" ]]; then
  sed -i \
      -e 's block/platform/msm_sdcc.1/by-name/modem mmcblk0p1 ' \
      -e 's block/platform/msm_sdcc.1/by-name/persist mmcblk0p20 ' \
      -e 's block/platform/msm_sdcc.1/by-name/system mmcblk0p21 ' \
      units/*.mount
fi

## asus/grouper
if [[ x"$DEVICE" = x"grouper" ]]; then
  sed -i \
      -e 's block/platform/sdhci-tegra.3/by-name/APP mmcblk0p3 ' \
      -e 's block/platform/sdhci-tegra.3/by-name/CAC mmcblk0p4 ' \
      -e 's block/platform/sdhci-tegra.3/by-name/UDA mmcblk0p9 ' \
      -e 's block/platform/sdhci-tegra.3/by-name/MSC mmcblk0p5 ' \
      -e 's block/platform/sdhci-tegra.3/by-name/LNX mmcblk0p2 ' \
      -e 's block/platform/sdhci-tegra.3/by-name/SOS mmcblk0p1 ' \
      units/*.mount
fi

## asus/tilapia
if [[ x"$DEVICE" = x"tilapia" ]]; then
  sed -i \
      -e 's block/platform/sdhci-tegra.3/by-name/APP mmcblk0p3 ' \
      -e 's block/platform/sdhci-tegra.3/by-name/CAC mmcblk0p5 ' \
      -e 's block/platform/sdhci-tegra.3/by-name/UDA mmcblk0p10 ' \
      -e 's block/platform/sdhci-tegra.3/by-name/MSC mmcblk0p6 ' \
      -e 's block/platform/sdhci-tegra.3/by-name/LNX mmcblk0p2 ' \
      -e 's block/platform/sdhci-tegra.3/by-name/SOS mmcblk0p1 ' \
      units/*.mount
fi

