#!/bin/sh
# Fix up mount points in unit files
# FIXME: Right now, this is mako-specific

# This is broken pending systemd > 191-2 so hack the generated unit files :(
# See: https://bugzilla.redhat.com/show_bug.cgi?id=859297
sed -i \
    -e 's block/platform/msm_sdcc.1/by-name/modem mmcblk0p1 ' \
    -e 's block/platform/msm_sdcc.1/by-name/persist mmcblk0p20 ' \
    -e 's block/platform/msm_sdcc.1/by-name/system mmcblk0p21 ' \
    units/*.mount
