# Feel free to disable non-critical HA parts during devel by commenting out
# Generated in hadk by executing: cd $ANDROID_ROOT; rpm/helpers/add_new_device.sh

Description: Pattern with packages for maguro configurations
Name: jolla-configuration-maguro
Requires:
- pattern:jolla-hw-adaptation-maguro
- pattern:jolla-configuration-sfe

Summary: Jolla Configuration maguro

