Description: Pattern with packages for @DEVICE@ configurations
Name: jolla-configuration-@DEVICE@
Requires:
- pattern:jolla-hw-adaptation-@DEVICE@
- pattern:jolla-configuration-sfe

Summary: Jolla Configuration @DEVICE@

